# Dockerfile.ubuntu
FROM ubuntu:latest

# 必要に応じてパッケージをインストール
RUN apt-get update && apt-get install -y \
  nginx \
  curl \
  vim \
  git \
  iproute2 \
  plocate \
  && rm -rf /var/lib/apt/lists/* \
  && updatedb

# RUN apt update && apt install -y \
#   iproute2 \
#   plocate \
#   && updatedb
# 作業ディレクトリを設定
WORKDIR /var/www

# Nginx の設定ファイルをコピー（必要に応じてカスタマイズ）
COPY nginx.conf /etc/nginx/nginx.conf

# ポート80を公開
EXPOSE 80

# コンテナが起動時に実行するコマンド
# CMD ["bash"]
CMD ["nginx", "-g", "daemon off;"]
